spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/app
    hikari:
      schema: certifications
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  # sql:
  #   init:
  #     schema-locations: certifications
# https://www.baeldung.com/spring-security-oauth-resource-server
  security:
    oauth2:
      resourceserver:
        jwt:
          # authority: "theapp.read"
          jwk-set-uri: http://keycloak.localhost:8082/realms/app/protocol/openid-connect/certs
          issuer-uri: http://keycloak.localhost:8082/realms/app 

management:
  endpoints:
    web:
      exposure:
        include: info,health

info:
  app:
    name: certifications-service
    description: Spring Boot microservice for managing certifications

server:
  port: 8081

logging:
  level: 
    org:
      springframework: 
        security: DEBUG
    com:
      nimbusds:
        jose: DEBUG    
